name: PR Template Checker

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: wp-media/pr-checklist-action@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
